name: tests

on:
  pull_request:
    branches: [ develop, main ]
  push:
    tags:
      - '*'

jobs:
  transaction:
    runs-on: ubuntu-latest
    steps:

    - name: checkout
      uses: actions/checkout@master

    - name: make .env
      uses: canastro/copy-file-action@master
      with:
        source: ".env-default"
        target: ".env"

    - name: setup
      uses: shivammathur/setup-php@master
      with:
        php-version: 5.6
        coverage: none

    - name: composer install
      run: composer install

    - name: phpunit
      run: vendor/bin/phpunit --colors="always"
